version: "3.8"
services:
  video_server:
    build: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
  swagger:
    image: swaggerapi/swagger-ui:v4.15.5
    ports:
      - "80:8080"
    volumes:
      - .:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/api.yaml
